---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-muppet.fullname" . }}
  labels:
    {{- include "kube-muppet.labels" . | nindent 4 }}
stringData:
  autosign_psk: {{ .Values.puppet.autosign_psk | quote }}
